# 数据集相关配置
dataset: whu                # 数据集名称
data_root: ./data/WHU-CD-256/  # 数据集根目录，修改为你的数据路径
exp: 48
nclass: 2                    # 类别数，通常是 2（变化/未变化）

img_scale: null              # 图像缩放大小，null 表示不缩放
scale_ratio_range: [0.5, 2.0] # 缩放比例范围
crop_size: 256               # 裁剪大小
labeled_photometric_distortion: false  # 是否开启有标注样本颜色扰动增强
# 模型相关配置
model: mmseg.vlm-lighthead-r50   # 模型名称，保持与代码匹配
model_args: {}                   # 传给模型的额外参数，通常为空字典

disable_dropout: true            # 训练时是否禁用 dropout
fp_rate: 0.5                    # 伪标签失真率参数

# 硬件相关配置
gpu_model: '5080'              # 显卡型号（仅作记录）
n_gpus: 1                     # 使用的GPU数量
n_nodes: 1                    # 计算节点数

# 评估相关配置
eval_mode: original           # 评估模式
eval_every_n_epochs: 1        # 每隔多少轮评估一次
nccl_p2p_disable: false       # NCCL点对点通信是否禁用

version: '0.10'               # 版本号
git_rev: ''                  # git版本号，非必须
